title: New Site Title
author: kitty
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  New side description after change to yml file.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
